### ISSUE TITLE
Refund Issue with Ingenico-ePayments module

### ISSUE THREAD

**Issue by marioestep** [Ingenico-ePayments/connect-extension-magento2#19]
Hello, we've come across and issue with this module.

We run a website with multiple currencies. The base currency of the website is Euro (€).

The moment the client purchases a product with a foreign currency, for example Dollar ($) and later on the client ask for a refund this is what happens in the website.

The clients currency, in our case Dollar is converted to Euro (the base currency of the website). And when the refund happens the base currency is converted to the clients currency.

Based on all these exchanges the client loses some money.

We don't want these exchanges to happen and we want our clients to be refunded the exact amount they have purchased in the website.

Magento 2 Version we use:  2.3.4
Ingenico Version:  2.4.5

Thank you

**Comment by kanduvisla** [comment]
Hi @marioestep ,

So if I understand you correctly: 

- The base currency on your website is EUR. 
- Let's say 1 EUR is 1.21 USD. 
- So a product of 1 EUR is displayed as 1.21 USD to your customer.
- The customer pays 1 EUR in the checkout (since this is the base currency).
- After a while a refund is asked, but at that moment the exchange rate has changed. Let's say 1 EUR is now 1.19 USD
- Since the base currency is still EUR, you create a credit memo (a refund) for 1 EUR.
- But since the exchange rate has changed, the customer get's refunded 1.19 USD in the end.

Is the above scenario the problem you are facing? Or is it something else?

**Comment by marioestep** [comment]
Hi, yes, that's exactly it.

**Comment by marioestep** [comment]
If a client purchases something in their own currency, I don't want them to be part of the currency exchange till the moment the Order is Approved.

**Comment by kanduvisla** [comment]
@marioestep Thank you

I'll have to investigate this further since it looks like this is something that has to do with how the API is built and the fact that Magento can only perform a checkout with the base currency.

I'll keep you updated using this ticket.

**Comment by marioestep** [comment]
Thank you!

**Comment by marioestep** [comment]
Hello I'd like to add these two screenshots, these are real orders in our site.

First Screenshot

![Screenshot_20210127-121239](https://user-images.githubusercontent.com/75430313/105983661-5824c680-6099-11eb-9557-281f99aa8685.png)

Second Screenshot

![-10000000094-Orders-Operations-Sales-Magento-Admin](https://user-images.githubusercontent.com/75430313/105983705-67a40f80-6099-11eb-9351-c9338ce17513.png)

Hopefully you get a better idea what seems to be the problem with the refund.

**Comment by sergiuec** [comment]
Is there any update on this issue?
we have now another case but now the currency is USD and of course the refund amount is too large.

`HTTP/1.1 400
Date: Fri, 26 Feb 2021 15:28:33 GMT
Server: Apache/2.4.39 (Unix) OpenSSL/1.1.1c
X-Cnection: close
Content-Type: application/json
Connection: close
Transfer-Encoding: chunked

{
    "errorId": "603913a22bfcac80da8be6ff3e0a142d",
    "errors": [
        {
            "code": "300430",
            "requestId": "xxxx",
            "message": "REFUND AMOUNT TOO LARGE",
            "httpStatusCode": 400
        }
    ]
} [] []
[2021-02-26 15:28:34] main.EMERGENCY: Unable to perform request using communicator configuration: The server returned an error. [] []`

Amount at backend of magento:
![View-Memo-for-Operations-Sales-Magento-Admin](https://user-images.githubusercontent.com/71697003/109321504-80971080-7851-11eb-8946-eb2f915b3c88.png)

Amount at ingenico backend is 507EURO

**Comment by Ingenico-Shoppingcarts** [comment]
@sergiuec I've been looking into the flow on our side Magento independent. 

We manage orders consumer facing without effecting the total amount due to exchange rate. 
An order of $100,- can always be matched in refunds total of $100,- 

Reflecting this to Magento we always use the base currency to process the transaction and the Display currencies are not used. 
This means if the base currency is EUR and the consumer views the product in Dollar. All communication to Ingenico. will be based on EUR. Authorization, Capture and Refund. 

We are planning for 2021 to have a module to work with the display currency instead of base currency. This would mean implementing a sub-module. It is now targeted for Q3.

In order to do understand the history of the order, if it is on production. Please share the ID to our Merchant services.
